### ISSUE TITLE
DiPho_digital v1.0 issues

### ISSUE THREAD

**Issue by pm-daniel** [sinara-hw/DiPho#16]
This issue is for tracking found mistakes/issues in DiPho_digital.PrjPcb
- [x] Missing P3V3 1k5 1% pull-up resistor on USB DP line (STM AN4879 page 4)

**Comment by pm-daniel** [comment]
- [ ] Missing P3V3 1k5 1% pull-up resistor on USB DP line (STM AN4879 page 4)

**Comment by pm-daniel** [comment]
2. - [ ] Add diagnostic ADC channels (f.e. 3V3, 4V7 voltage sense) in future revision

**Comment by pm-daniel** [comment]
3. - [ ] Revise the ethernet circuitry

**Comment by gkasprow** [comment]
- [ ] add passive PoDL circuit with reverse protection
- [ ] make two dedicated AFE boards? 
- [ ] use low profile USB connector
- [ ] replace big SMA connector with small MCX connector and make room for twisted pair connector

**Comment by pm-daniel** [comment]
- [ ] provide another point of support between PCBs apart from the mezzanine connector
